# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 贾景晗
description: 贾景晗的主页
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: 作品集
    - name: 博客

footer:
  show_powered_by: true
  contact:
    - type: email
      name: 邮箱
      value: 1255105284@qq.com

  follow:
    - type: RedNote
      name: 小红书
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    - type: TikTok
      name: 抖音
      link: http://facebook.com/YourFacebookUsername


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
