# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 贾景晗
description: 目前在鲁迅美术学院攻读研究生学位，研究方向为视觉传达设计。此前在该校完成本科阶段学习，系统掌握了包装设计、海报设计、广告摄影、书籍装帧、新媒体艺术设计等课程内容，专业基础扎实，设计视野开阔。在校期间积极参与各类视觉艺术实践项目，创作经验丰富。曾围绕鲁迅名著《社戏》《呐喊》发表一百周年，设计纪念酒包装，并成功落地发布，作品结合文学与视觉叙事，体现出高度的文化理解与创意表达能力。此外，多次在全国性赛事中获奖，包括“全国美术院校读书主题艺术创作大赛”“‘东北人2050’海报设计大赛”等，具备优秀的项目执行力与艺术创作实力。精通AI、PS、AE、PR、C4D等主流视觉设计与剪辑软件，技术全面。性格沉稳，具备良好的沟通协作能力和抗压能力，致力于在视觉传达与文化创意设计领域持续深耕与创新。
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
      slug: /
    - name: 作品集
    - name: 博客

footer:
  show_powered_by: true
  contact:
    - type: email
      name: 邮箱
      value: 1255105284@qq.com

  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/YourTwitterUsername
      username: "@YourTwitterUsername"
    - type: facebook
      name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
